Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.define "hmaciel-S" do |node|
    node.vm.hostname = "hmaciel-S"
    node.vm.network "private_network",
      ip: "192.168.56.110",
      libvirt__network_name: "vagrant-libvirt",
      libvirt__mac: "52:54:00:aa:bb:01"
    node.vm.provider :libvirt do |libvirt|
      libvirt.memory = 512
      libvirt.cpus = 1
    end
  end

  config.vm.define "maria-SW" do |node|
    node.vm.hostname = "maria-SW"
    node.vm.network "private_network",
      ip: "192.168.56.111",
      libvirt__network_name: "vagrant-libvirt",
      libvirt__mac: "52:54:00:aa:bb:02"
    node.vm.provider :libvirt do |libvirt|
      libvirt.memory = 512
      libvirt.cpus = 1
    end
  end
end
